version: "3"

services:
  mysql:
    build:
      context: ./mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306

  spring-boot-docker:
    build: .
    container_name: spring-boot
    ports:
      - 8080:8080
    depends_on:
      - mysql
    links:
      - mysql