CREATE DATABASE IF NOT EXISTS spring_test DEFAULT CHARSET=latin1;

USE spring_test;

CREATE TABLE IF NOT EXISTS payment (
  id int(11) unsigned NOT NULL AUTO_INCREMENT,
  type varchar(30) NULL,
  value decimal(20,2) NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

  PRIMARY KEY (id)
);